version: "3"
services:
  web:
    build:
      context: ./
    privileged: true
    volumes:
    - "../app/:/usr/local/app"
    ports:
      - 80:80
      - 3000:3000
    container_name: "nuxt-docker-stg"
    environment:
      - NODE_ENV=staging
